version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - wastedassign
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      enable:
        - shadow
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: internal/scanner/fs\.go
        text: G304
      - linters:
          - gosec
        path: internal/rules/loader\.go
        text: G304
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
