version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    # Allow G304 in scanner/fs.go and rules/loader.go - paths are validated
    - path: internal/scanner/fs\.go
      linters:
        - gosec
      text: "G304"
    - path: internal/rules/loader\.go
      linters:
        - gosec
      text: "G304"
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
